name: muninn
options:
  bundleIdPrefix: com.personal
  deploymentTarget:
    iOS: "18.0"
  generateEmptyDirectories: true

packages:
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    from: "9.1.2"

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: SHQSDJG35Q

targets:
  Muninn:
    type: application
    platform: iOS
    sources:
      - Muninn
    dependencies:
      - package: FeedKit
    settings:
      base:
        INFOPLIST_FILE: Muninn/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.personal.muninn
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        MARKETING_VERSION: "0.5"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Muninn/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDisplayName: Muninn

schemes:
  Muninn:
    build:
      targets:
        Muninn: all
    run:
      config: Debug
